#!/usr/bin/env bash

echo_white() {
	echo $'\e[01;0m'"${1}"$'\e[0m'"${2}"
}

echo_gray() {
	echo $'\e[01;30m'"${1}"$'\e[0m'"${2}"
}

echo_red() {
	echo $'\e[01;31m'"${1}"$'\e[0m'"${2}"
}

echo_green() {
	echo $'\e[01;32m'"${1}"$'\e[0m'"${2}"
}

echo_yellow() {
	echo $'\e[01;33m'"${1}"$'\e[0m'"${2}"
}

echo_blue() {
	echo $'\e[01;34m'"${1}"$'\e[0m'"${2}"
}

echo_violet() {
	echo $'\e[01;35m'"${1}"$'\e[0m '"${2}"
}

#Variables
IS_MAC=N
if [ "$(uname -s)" = "Darwin" ]; then
	IS_MAC=Y
	SED="gsed"
else
	SED="sed"
fi
DEBUG=0
TV_CHANNEL_CONF="tvchannel.conf"
WORKING_DIR=
if [ -d "/dev/shm" -a -w "/dev/shm" ]; then
	if [ "${DEBUG}" = 0 ] ; then
		WORKING_DIR="/dev/shm/epg2xml_${USER}"
	else
		WORKING_DIR=./working
	fi
else
	WORKING_DIR=./working
fi
COUNT="${WORKING_DIR}/count"
BASE_URL_NAVER='http://tvguide.naver.com/program/multiChannel.nhn?broadcastType={var1}&channelGroup={var2}&date={date}'
BASE_URL_EPG='http://schedule.epg.co.kr/new/tvguide/tvguide.php?search_top_channel_group={var1}&old_top_channel_group={var1}&search_sub_channel_group={var2}&old_sub_channel_group={var2}&ymd={date}&{channel}'
BASE_URL_EPG_CHECKCHANNEL='checkchannel%5B{var1}%5D={var2}'
WORKING_NAVER="${WORKING_DIR}/working_naver"
WORKING_EPG="${WORKING_DIR}/working_epg"
OUTPUT_FILE="${WORKING_DIR}/xmltv.xml"
XMLTV_FILE="./xmltv.xml.gz"
TIMESTAMP=".timestamp"

fn_validation() {
	if [ ! -e "${TV_CHANNEL_CONF}" ]; then
		echo "Cannot find ${TV_CHANNEL_CONF}"
		exit 1
	fi
	if [ -z "$(which "${SED}")" ]; then
		echo_red " -> " "Cannot found ${SED}"
		if [ "${IS_MAC}" = "Y" ]; then
			echo_red "    " "Pleas install brew gnu-sed package"
		fi
		exit 1
	fi
	if [ -z "$(which flock)" ]; then
		echo_red " -> " "Cannot found flock"
		if [ "${IS_MAC}" = "Y" ]; then
			echo_red "    " "Pleas install brew scoteq/discoteq/flock package"
		fi
		exit 1
	fi
	mkdir -p "${WORKING_DIR}" &> /dev/null
	if [ "${?}" != "0" ]; then
		echo_red " -> " "Cannot make working directory(${WORKING_DIR})"
		exit 1
	fi
	if [ ! -w "${WORKING_DIR}" -o ! -r "${WORKING_DIR}" ]; then
		echo_red " -> " "Cannot access working directory(${WORKING_DIR})"
		exit 1
	fi
	if [ "${DEBUG}" = "0" -a -e "${TIMESTAMP}" -a "${OUTPUT_FILE}" ]; then
		if [ "$(wc -l < "${TIMESTAMP}")" = "3" ]; then
			local md5sum_prev="$(head -n 1 "${TIMESTAMP}")"
			local datetime_prev="$("${SED}" -n "2,1p" "${TIMESTAMP}")"

			if [ ! -z "${md5sum_prev}" -a ! -z "${datetime_prev}" ]; then
				local md5sum="$(fn_md5 "${TV_CHANNEL_CONF}")"
				local datetime_prev_s="$(date -d "${datetime_prev}" +%s)"
				local datetime_s="$(date +%s)"

				if [ "${md5sum}" = "${md5sum_prev}" -a $((datetime_s - $datetime_prev_s)) -lt 3600 ]; then
					echo_yellow "Alread up-to date ($(date -d "${datetime_prev}" "+%F %T"))"
					exit 1
				fi
			fi
		fi
	fi
}

fn_prepare() {
	fn_md5 "${TV_CHANNEL_CONF}" > "${TIMESTAMP}"
	date +"%F %T" >> "${TIMESTAMP}"

	if [ "${DEBUG}" = "0" ]; then
		rm -rf "${WORKING_DIR}"
	fi
	mkdir -p "${WORKING_DIR}" &> /dev/null
	if [ "${?}" != "0" ]; then
		echo "Cannot make working directory(${WORKING_DIR})"
		exit 1
	fi
	touch "${OUTPUT_FILE}"

	fn_count_reset
}

fn_md5() {
	if [ "${IS_MAC}" = "Y" ]; then
		md5 "${1}" | "${SED}" -e 's/^.*= \(.*\)$/\1/g'
	else
		md5sum "${1}" | "${SED}" -e 's/^\(.*\)[[:space:]]\+.*/\1/g'
	fi
}

fn_count_reset() {
	(
		while ! flock -w 10 100
		do
			sleep 0.1
		done
		echo 1 > "${COUNT}"
	) 100>"${COUNT}.lock"
}

fn_count_get() {
	(
		while ! flock -w 10 200
		do
			sleep 0.1
		done
		local count=$(cat "${COUNT}")
		echo $((count + 1)) > "${COUNT}"
		echo ${count}
	) 200>"${COUNT}.lock"
}

fn_file_write() {
	(
		while ! flock -w 10 300
		do
			sleep 0.1
		done
		if [ -z "${2}" ]; then
			while read -r data
			do
				echo "${data}" >> "${1}"
			done
		else
			echo "${2}" >> "${1}"
		fi
	) 300>"${1}.lock"
}

fn_download_naver() {
	local download_list=()

	echo_blue " -> " "Generate Download URL(naver)"

	local channels="$("${SED}" -e '/^[^#].*,.*:N,.*,.*,.*,.*$/!d' "${TV_CHANNEL_CONF}")"
	local channel_filter="$("${SED}" -e 's/^.*,.*:N,\(.*\),.*,\(.*\),.*$/\1,\2,/g' <<< "${channels}" | "${SED}" -e ':a;N;$!ba;s/\n/\\|/g')"

	local line=
	while read -r line
   	do
		local var1="$("${SED}" -e 's/^\(.*\),.*/\1/g' <<< "${line}")"
		local var2="$("${SED}" -e 's/^.*,\(.*\)/\1/g' <<< "${line}")"

		local url="${BASE_URL_NAVER}"
		url="${url//\{var1\}/${var1}}"
		url="${url//\{var2\}/${var2}}"
		download_list+=("${url}")
	done <<< "$("${SED}" -e 's/^.*,.*:N,\(.*,.*\),.*,.*$/\1/g' <<< "${channels}" | sort -u)"

	echo_blue " -> " "Done."

	echo_blue " -> " "Start Download(naver)"

	cat /dev/null > "${WORKING_NAVER}"

	local day=
	for day in 0 1
	do
		fn_count_reset

		local date="$(date +%Y%m%d -d "${day} days")"
		local date_display="$(date +%Y-%m-%d -d "${day} days")"

		for url in ${download_list[@]}
		do
			while [ $(jobs -rp | wc -l) -ge 8 ]
			do
				sleep 0.1
			done

			echo -ne " -> ${date_display} $(fn_count_get)/${#download_list[@]}\033[0K\r"
			curl -s "${url/\{date\}/${date}}" | "${SED}" -e '/[[:space:]]*"broadcastType" :\|[[:space:]]*"channelId" :\|[[:space:]]*"programList" :/!d' -e 's/^[[:space:]]\+//' | "${SED}" -e '/^"broadcastType\".*/ {N;N; s/\"broadcastType\" : \([[:digit:]]*\),.*\"channelId\" : \([[:digit:]]*\),.*\(\"programList\" :.*\)$/\1,\2,\3/g}' | "${SED}" -e "/${channel_filter}/!d" | "${SED}" -e 's/&/&amp;/g' -e 's/>/\&gt;/g' -e 's/</\&lt;/g' -e 's/%/\&#37;/g' | fn_file_write "${WORKING_NAVER}" &
		done

		wait

		echo
	done

	wait

	echo_blue " -> " "Done."
}

fn_download_epg() {
	local download_list=()

	echo_blue " -> " "Generate Download URL(epg)"

	local channels="$("${SED}" -e '/^[^#].*,.*:E,.*,.*,.*,.*$/!d' "${TV_CHANNEL_CONF}")"

	local line=
	while read -r line
	do
		local var1="$("${SED}" -e 's/^\(.*\),.*$/\1/g' <<< "${line}")"
		local var2="$("${SED}" -e 's/^.*,\(.*\)$/\1/g' <<< "${line}")"
		local checkchannel=
		local loop_seq=1
		local line=
		while read -r channel
	   	do
			local check="$("${SED}" -e 's/^.*:E,.*,.*,\(.*\),.*$/\1/g' <<< "${channel}")"
			local channelno="$("${SED}" -e 's/^\(.*\),.*:E,.*,.*,.*,.*$/\1/g' <<< "${channel}")"
			local checkchannel_curr="${BASE_URL_EPG_CHECKCHANNEL}"
			checkchannel_curr="${checkchannel_curr//\{var1\}/${check}}"
			checkchannel_curr="${checkchannel_curr//\{var2\}/${channelno}}"
			checkchannel+="${checkchannel_curr}&"

			if [ "$((loop_seq % 5))" = "0" ]; then
				local url="${BASE_URL_EPG}"
				url="${url//\{var1\}/${var1}}"
				url="${url//\{var2\}/${var2}}"
				url="${url//\{channel\}/${checkchannel}}"
				download_list+=("${url}")
				checkchannel=""
			fi

			loop_seq=$((loop_seq + 1))
		done <<< "$("${SED}" -e "/^.*,.*:E,${var1},${var2},.*,.*/!d" <<< "${channels}")"

		if [ ! -z "${checkchannel}" ]; then
			local url="${BASE_URL_EPG}"
			url="${url//\{var1\}/${var1}}"
			url="${url//\{var2\}/${var2}}"
			url="${url//\{channel\}/${checkchannel}}"
			download_list+=("${url}")
			checkchannel=""
		fi
	done <<< "$("${SED}" -e 's/^.*,.*:E,\(.*,.*\),.*,.*$/\1/g' <<< "${channels}" | sort -u)"

	echo_blue " -> " "Done."

	echo_blue " -> " "Start Download(epg)"

	cat /dev/null > "${WORKING_EPG}"
	local year="$(date +%Y)"

	local day=
	for day in 0 1
	do
		fn_count_reset

		local date="$(date +%Y-%m-%d -d "${day} days")"

		for url in ${download_list[@]}
		do
			while [ $(jobs -rp | wc -l) -ge 8 ]
			do
				sleep 0.1
			done

			echo -ne " -> ${date} $(fn_count_get)/${#download_list[@]}\033[0K\r"
			curl -s "${url/\{date\}/${date}}" | iconv -f cp949 -t utf-8 | "${SED}" -e '/onMouseOver=\"Preview(/!d' -e 's/.*onMouseOver=\"Preview(\(.*\))\" onMouseOut=.*$/\1/g' -e 's/<br>//g' -e "s/\\\'/'/g" | "${SED}" -e "s/^'.*',\('.*','.*'\),'\(.*\) \(.*\) \(.*\)~\(.*\) \(.*\) \(.*\)',\('.*','.*','.*'\)/\1,'${year}\/\2 \4 \3','${year}\/\5 \7 \6',\8/g" | fn_file_write "${WORKING_EPG}" &
		done

		wait

		echo

	done

	wait

	echo_blue " -> " "Done."
}

fn_download() {
	echo_green "==> " "Start Download"

	fn_download_naver

	fn_download_epg

	echo_green "==> " "Done."
	echo
}

fn_generate_xml_header() {
	echo_blue " -> " "Generate Header"

	local result=
	read -r -d '' result << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">

<tv source-info-name="epg.co.kr" generator-info-name="forumi0721" generator-info-url="mailto:forumi0721@gmail.com">
EOF
	fn_file_write "${OUTPUT_FILE}" "${result}"

	echo_blue " -> " "Done."
}

fn_generate_xml_channel() {
	echo_blue " -> " "Generate Channel"

	fn_count_reset

	local channels="$("${SED}" -e '/^#/d' -e 's/^\(.*\):\+.*$/\1/g' "${TV_CHANNEL_CONF}")"
	local channels_count="$(wc -l <<< "${channels}")"

	local line=
	while read -r line
	do
		echo -ne " -> $(fn_count_get)/${channels_count}\033[0K\r"
		local channel_no="$("${SED}" -e 's/^\(.*\),.*/\1/g' <<< "${line}")"
		local channel_name="$("${SED}" -e 's/^.*,\(.*\)/\1/g' -e 's/&/&amp;/g' -e 's/>/\&gt;/g' -e 's/</\&lt;/g' -e 's/%/\&#37;/g' -e 's/&amp;amp;/\&amp;/g' -e 's/&amp;gt;/\&gt;/g' -e 's/&amp;lt;/\&lt;/g' -e 's/&amp;#37;/\&#37;/g' <<< "${line}")"

		if [ -z "${channel_no}" -o -z "${channel_name}" ]; then
			continue
		fi

		local result=
		read -r -d '' result << EOF
<channel id="I${channel_no}.schedule.epg.co.kr">
	<display-name>${channel_no} ${channel_name}</display-name>
	<display-name>${channel_no}</display-name>
	<display-name>${channel_name}</display-name>
</channel>
EOF
		fn_file_write "${OUTPUT_FILE}" "${result}"
	done <<< "${channels}"

	echo
	echo_blue " -> " "Done."
}

fn_generate_xml_programme_naver() {
	echo_blue " -> " "Generate Programme(naver)"

	fn_count_reset

	local total_count="$("${SED}" -e 's/scheduleName/scheduleName\n/g' "${WORKING_NAVER}" | "${SED}" -e '/scheduleName/!d' | wc -l)"
	
	local line=
	while read -r line
	do
		local channel="$("${SED}" -e 's/^\(.*\),.*:N,.*,.*,.*,.*$/\1/g' <<< "${line}")"
		if [ -z "${channel}" -o "${channel}" = "${line}" ]; then
			echo_red " -> " "${channel} Not found"
			continue
		fi
		local channel_filter="$("${SED}" -e 's/^.*,.*:N,\(.*\),.*,\(.*\),.*$/\^\1,\2,/g' <<< "${line}")"
		local pgm_list=
		while read -r pgm_list
		do
			if [ -z "${pgm_list}" ]; then
				echo_red " -> " "${channel} Not found"
				continue
			fi

			while [ $(jobs -rp | wc -l) -ge 8 ]
			do
				sleep 0.1
			done

			fn_generate_xml_programme_naver_thread "${channel}" "${pgm_list}" "${total_count}" &
		done <<< "$("${SED}" -e "/${channel_filter}/!d" "${WORKING_NAVER}")"
	done <<< "$("${SED}" -e '/:N,/!d' "${TV_CHANNEL_CONF}")"

	wait

	echo
	echo_blue " -> " "Done."
}

fn_generate_xml_programme_naver_thread() {
	local channel="${1}"
	local pgm_list="${2}"
	local total_count="${3}"

	local pgm=
	while read -r pgm
	do
		echo -ne " -> $(fn_count_get)/${total_count}\033[0K\r"

		local begin_time="$("${SED}" 's/^.*"beginDate":"\([^\"]*\)",.*"beginTime":"\([^\"]*\)",.*/\1 \2/g' <<< "${pgm}")"
		local runtime="$("${SED}" 's/^.*"runtime":\([^,]*\),.*/\1/g' <<< "${pgm}")"

		local start="$(date -d "${begin_time}" '+%Y%m%d%H%M%S %z')"
		local end="$(date -d "${begin_time} ${runtime} minutes" '+%Y%m%d%H%M%S %z')"
	
		local title="$("${SED}" 's/^.*"scheduleName":"\(.*\)","beginDate":.*$/\1/g' <<< "${pgm}")"
		local subtitle="$("${SED}" 's/^.*"subtitle":"\(.*\)","signLanguage":.*$/\1/g' <<< "${pgm}")"
		local episode="$("${SED}" 's/^.*"episodeNo":"\(.*\)","live":.*$/\1/g' <<< "${pgm}")"
		local category="$("${SED}" 's/^.*"largeGenreId":"\([[:alnum:]]*\)","episodeNo":.*$/\1/g' <<< "${pgm}")"
		local category_en=
		case ${category} in
			A) #드라마
				category="드라마"
				category_en="Movie / Drama"
			   	;;
			B) #영화
				category="영화"
				category_en="Movie / Drama"
			   	;;
			C) #만화
				category="만화"
				category_en="Children's / Youth programmes"
				;;
			D) #연애/오락
				category="연애/오락"
				category_en="Show / Games"
				;;
			E) #스포츠
				category="스포츠"
				category_en="Sports"
				;;
			F) #취미/레저
			   	category="취미/레저"
			   	category_en="Leisure hobbies"
				;;
			G) #음악
				category="음악"
				category_en="Music / Ballet / Dance"
				;;
			H) #교육
				category="교육"
				category_en="Education / Science / Factual topics"
				;;
			I) #뉴스
				category="뉴스"
				category_en="News / Current affairs"
				;;
			J) #시사/다큐
				category="시사/다큐"
				category_en="Social / Political issues / Economics"
				;;
			K) #교양/정보
				category="교양/정보"
				category_en="Arts / Culture (without music)"
			   	;;
			L) #홍쇼핑
				category="홈쇼핑"
				category_en=""
				;;
			*) #기타
				category=""
				category_en=""
				;;
		esac

		local rating="$("${SED}" 's/^.*"ageRating":\(.*\),"subtitle":.*$/\1/g' <<< "${pgm}")"

		local desc="${title}"
		if [ ! -z "${subtitle}" ]; then
			desc+=" &lt;${subtitle}&gt;"
		fi
		if [ ! -z "${episode}" ]; then
			desc+=" (${episode})"
		fi
	
		local result=
		read -r -d '' result << EOF
<programme start="${start}" stop="${end}" channel="I${channel}.schedule.epg.co.kr">
	<title lang="ko">${title}</title>
	<sub-title lang="ko">${subtitle}</sub-title>
	<desc lang="ko">${desc}</desc>
	<episode-num system="onscreen">${episode}</episode-num>
	<category lang="en">${category_en}</category>
	<category lang="ko">${category}</category>
	<language>ko</language>
	<rating system="VCHIP">
		<value>${rating}</value>
	</rating>
</programme>
EOF
		fn_file_write "${OUTPUT_FILE}" "${result}"
	done <<< "$("${SED}" -e "s/^.*\"programList\":\[\(.*\)\]/\1/g" -e "s/},{/\n/g" <<< "${pgm_list}")"
}

fn_generate_xml_programme_epg() {
	echo_blue " -> " "Generate Programme(epg)"

	fn_count_reset

	local total_count="$(wc -l < "${WORKING_EPG}")"

	local line=
	while read -r line
	do
		while [ $(jobs -rp | wc -l) -ge 8 ]
		do
			sleep 0.1
		done

		echo -ne " -> $(fn_count_get)/${total_count}\033[0K\r"
		fn_generate_xml_programme_epg_thread "${line}" &
	done < "${WORKING_EPG}"

	wait

	echo
	echo_blue " -> " "Done."

}

fn_generate_xml_programme_epg_thread() {
	local line="${1}"

	local title="$("${SED}" -e "s/^'\(.*\)','.*','.*','.*','.*','.*','.*'/\1/g" <<< "${line}")"

	local episode="$("${SED}" -e "s/^.*(\([[:digit:]]\+회\))/\1/g" <<< "${title}")"
	if [ "${episode}" = "${title}" ]; then
		episode=""
	else
		title="$("${SED}" -e "s/^\(.*\)[[:space:]]*([[:digit:]]\+회)/\1/g" <<< "${title}" | "${SED}" -e 's/[[:space:]]\+$//g')"
	fi

	local subtitle="$("${SED}" -e "s/^.*&lt;\(.*\)&gt;$/\1/g" <<< "${title}")"
	if [ "${subtitle}" = "${title}" ]; then
		subtitle=""
	else
		title="$("${SED}" -e "s/^\(.*\)[[:space:]]*&lt;.*&gt;$/\1/g" <<< "${title}" | "${SED}" -e 's/[[:space:]]\+$//g')"
	fi

	local desc="${title}"
	if [ ! -z "${subtitle}" ]; then
		desc+=" &lt;${subtitle}&gt;"
	fi
	if [ ! -z "${episode}" ]; then
		desc+=" (${episode})"
	fi

	local start="$("${SED}" -e "s/^'.*','.*','\(.*\)','.*','.*','.*','.*'/\1/g" <<< "${line}")"
	start="$(date -d "${start}" '+%Y%m%d%H%M%S %z')"

	local end="$("${SED}" -e "s/^'.*','.*','.*','\(.*\)','.*','.*','.*'/\1/g" <<< "${line}")"
	end="$(date -d "${end}" '+%Y%m%d%H%M%S %z')"

	local channel_no="$("${SED}" -e "s/^'.*','\(.*\)','.*','.*','.*','.*','.*'/\1/g" <<< "${line}")"
	local category="$("${SED}" -e "s/^'.*','.*','.*','.*','\(.*\)','.*','.*'/\1/g" <<< "${line}")"
	local category_en=
	case ${category//-*/} in
		드라마) #드라마
			category="드라마"
			category_en="Movie / Drama"
			;;
		영화) #영화
			category="영화"
			category_en="Movie / Drama"
			;;
		만화) #만화
			category="만화"
			category_en="Children's / Youth programmes"
			;;
		연애/오락) #연애/오락
			category="연애/오락"
			category_en="Show / Games"
			;;
		스포츠) #스포츠
			category="스포츠"
			category_en="Sports"
			;;
		취미/레저) #취미/레저
			category="취미/레저"
			category_en="Leisure hobbies"
			;;
		음악) #음악
			category="음악"
			category_en="Music / Ballet / Dance"
			;;
		교육) #교육
			category="교육"
			category_en="Education / Science / Factual topics"
			;;
		뉴스) #뉴스
			category="뉴스"
			category_en="News / Current affairs"
			;;
		시사/다큐) #시사/다큐
			category="시사/다큐"
			category_en="Social / Political issues / Economics"
			;;
		교양/정보) #교양/정보
			category="교양/정보"
			category_en="Arts / Culture (without music)"
			;;
		홈쇼핑) #홍쇼핑
			category="홈쇼핑"
			category_en=""
			;;
		*) #기타
			category=""
			category_en=""
			;;
	esac
	local actor="$("${SED}" -e "s/^'.*','.*','.*','.*','.*','\(.*\)','.*'/\1/g" <<< "${line}")"

	local result=
	read -r -d '' result << EOF
<programme start="${start}" stop="${end}" channel="I${channel_no}.schedule.epg.co.kr">
	<title lang="ko">${title}</title>
	<sub-title lang="ko">${subtitle}</sub-title>
	<desc lang="ko">${desc}</desc>
	<episode-num system="onscreen">${episode}</episode-num>
	<category lang="en">${category_en}</category>
	<category lang="ko">${category}</category>
	<language>ko</language>
	<credits>
		<actor>${actor}</actor>
	</credits>
</programme>
EOF
	fn_file_write "${OUTPUT_FILE}" "${result}"
}

fn_generate_xml_programme() {
	if [ -e "${WORKING_NAVER}" ]; then
		fn_generate_xml_programme_naver
	fi

	if [ -e "${WORKING_EPG}" ]; then
		fn_generate_xml_programme_epg
	fi
}

fn_generate_footer() {
	echo_blue " -> " "Generate Footer"
	local result=
	read -r -d '' result << EOF
</tv>
EOF
	fn_file_write "${OUTPUT_FILE}" "${result}"
	echo_blue " -> " "Done."
}

fn_generate_xml() {
	echo_green "==> " "Generate XML"

	fn_generate_xml_header

	fn_generate_xml_channel

	fn_generate_xml_programme

	fn_generate_footer

	echo_green "==> " "Done."
	echo
}

fn_cleanup() {
	echo_green "==> " "Cleanup"

	wait

	"${SED}" -i -e '/<sub-title lang="ko"><\/sub-title>/d' -e '/<episode-num system="onscreen"><\/episode-num>/d' -e '/[[:space:]]*<rating system="VCHIP">.*/ {N;N; /[[:space:]]*<rating system="VCHIP">.*<value>0\?<\/value>.*<\/rating>/d}' -e '/[[:space:]]*<credits>.*/ {N;N; /[[:space:]]*<credits>.*<actor><\/actor>.*<\/credits>/d}' "${OUTPUT_FILE}"

	if [ "${XMLTV_FILE//\.gz/}" != "${XMLTV_FILE}" ]; then
		gzip -9 "${OUTPUT_FILE}"
		mv "${OUTPUT_FILE}.gz" "${XMLTV_FILE}"
	else
		mv "${OUTPUT_FILE}" "${XMLTV_FILE}"
	fi
	if [ "${DEBUG}" = "0" ]; then
		rm -rf "${WORKING_DIR}"
	fi

	date +"%F %T" >> "${TIMESTAMP}"

	echo_green "==> " "Done."
	echo
}

#Validation
fn_validation

#Prepare
fn_prepare

#Download
fn_download

#Generate XML
fn_generate_xml

#Cleanup
fn_cleanup

exit

