#!/bin/bash

if [ -z "$1" ]; then
	cat /var/lib/scepg/xmltv.xml
	exit $?
fi

case "$1" in
	--description)
	echo "EPG grabber(scepg)"
	;;

	--version)
	echo "1.0"
	;;

	--capabilities)
	echo "baseline"
	;;
esac
